<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Academy</name>
   <tag></tag>
   <elementGuidId>091403b6-b522-4def-b74d-0a0333a1d926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#brxe-hjypyy > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='brxe-hjypyy']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#brxe-hjypyy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9ebb2ec-a068-41fd-a97d-01d92f8409c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5a8f412-c11c-4760-b4bf-3f09b5d00e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Academy</value>
      <webElementGuid>75db1511-6ebf-4b8c-98ce-b34186149069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brxe-hjypyy&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>3fe8f7a3-563e-4aab-8ae0-d9efef35a771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='brxe-hjypyy']/span[2]</value>
      <webElementGuid>9fa90dea-a531-4727-915a-2a4798f8db4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academy'])[1]/following::span[2]</value>
      <webElementGuid>a7242f9f-228d-49d0-8b0d-9699c201e19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::span[4]</value>
      <webElementGuid>17a54a4c-0b1d-467f-9329-a9a181e6f8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brightest'])[1]/preceding::span[1]</value>
      <webElementGuid>e9d1703b-ae66-4f01-a6fa-1a8464f84490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='software testing solutions'])[1]/preceding::span[1]</value>
      <webElementGuid>60c7e380-1a07-4ac4-b1c6-b29611e91b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span[2]</value>
      <webElementGuid>8e489ff4-95b3-4c13-ba83-5e0ff429c4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Academy' or . = 'Academy')]</value>
      <webElementGuid>00d33639-c7d2-4d7c-86f4-be1b071d0d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
