<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_casino</name>
   <tag></tag>
   <elementGuidId>7584619a-7f70-47d8-bdfd-7b38e8a493fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.navigation-context-list.active.secondary > li.navigation-context-list__item > a.global-header-product-switcher.sds-focus-alt.e2e-nav-casino-switch > span.global-header-product-switcher__label.capitalize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header/div/div/div[2]/ul[2]/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; casino&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cbda9232-f88f-46eb-bdc7-b5081f0ee0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>global-header-product-switcher__label capitalize</value>
      <webElementGuid>168a877e-72ef-45a8-a309-96a8c35f01ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>casino</value>
      <webElementGuid>b8381726-90e7-4b98-a7ef-f2df24133b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[@class=&quot;header header--fixed&quot;]/div[@class=&quot;header__content&quot;]/div[@class=&quot;header__left&quot;]/div[@class=&quot;navigation-contexts&quot;]/ul[@class=&quot;navigation-context-list active secondary&quot;]/li[@class=&quot;navigation-context-list__item&quot;]/a[@class=&quot;global-header-product-switcher sds-focus-alt e2e-nav-casino-switch&quot;]/span[@class=&quot;global-header-product-switcher__label capitalize&quot;]</value>
      <webElementGuid>f15aa408-3a86-4d7e-8ef4-4454d9bb0131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header/div/div/div[2]/ul[2]/li/a/span</value>
      <webElementGuid>6c0e0b99-212f-4f7f-a45e-54577590b329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='casino'])[1]/following::span[1]</value>
      <webElementGuid>9d09101c-3a26-4695-a616-a8f58572b445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sports'])[1]/following::span[3]</value>
      <webElementGuid>b9951954-4d8d-458b-9e63-b949e6f36aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sports'])[2]/preceding::span[2]</value>
      <webElementGuid>93e3b1b8-5e2a-4715-bf74-24c448ab81a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='register'])[1]/preceding::span[3]</value>
      <webElementGuid>4089024f-33d4-44ef-b796-84615cb7507e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a/span</value>
      <webElementGuid>fdf13cf6-a35e-4368-adbc-6392994c5e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'casino' or . = 'casino')]</value>
      <webElementGuid>320882c8-3a9c-4a4c-89f6-f2d9a75a1661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
