<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>031c3581-1440-4082-a1e3-4b5df9506446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pngCasinoGame']/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>781eebb6-b13d-4d81-9111-90ce35f7dddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1426</value>
      <webElementGuid>9141f544-616f-4336-a476-1081c60dca2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>802</value>
      <webElementGuid>07104c36-4067-47c6-98d2-bbb190a29e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pngCasinoGame&quot;)/canvas[1]</value>
      <webElementGuid>ad6614a7-6a39-4117-9b6e-2be848ea8d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Playing Super Flip Online  Play for Fr_b03df3/iframe_concat(id(, , gameWindow, , ))_gameWindow</value>
      <webElementGuid>e78b8729-9994-4eb0-af60-e9590a9e2167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pngCasinoGame']/canvas</value>
      <webElementGuid>9eca836e-b782-45cc-9221-8fad94b0638f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>d777a0f3-9b87-4c12-be89-32cea8183e96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
