<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , gameWindow, , ))_gameWindow</name>
   <tag></tag>
   <elementGuidId>faa34a76-aa9d-4323-810d-dfa98015ea58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gameWindow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gameWindow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gameWindow</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8f68f9dd-0d4a-4511-89df-48d47f4f430e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://aeucw.playngonetwork.com/casino/ContainerLauncher?pid=1490&amp;gid=superflip&amp;lang=en_GB&amp;demo=2&amp;user=token&amp;practice=1&amp;channel=desktop&amp;div=pngCasinoGame&amp;embedmode=iframe&amp;lobby=https://www.napoleongames.be&amp;origin=https://play-rgs.oryxgaming.com/&amp;isGameBridge=true</value>
      <webElementGuid>303444d2-8a9b-466e-a6d1-fe59f55ab6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gameWindow</value>
      <webElementGuid>663dcdf2-abf6-4d91-9d4a-1150f3cb9a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameWindow&quot;)</value>
      <webElementGuid>53888fb3-0a5d-48d8-b67a-bbe0a39e85e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Playing Super Flip Online  Play for Fr_b03df3/iframe_Play with money_iframe</value>
      <webElementGuid>0b564f5d-dd5f-4f06-b1c9-14242ea922d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gameWindow']</value>
      <webElementGuid>e1de5f6d-7a02-4034-9c48-1136499a918a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameContainer']/iframe</value>
      <webElementGuid>7612537b-06cf-4ec7-842c-31c07a27a9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6d2cf43c-e7c5-47a3-966a-9f2caef13693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://aeucw.playngonetwork.com/casino/ContainerLauncher?pid=1490&amp;gid=superflip&amp;lang=en_GB&amp;demo=2&amp;user=token&amp;practice=1&amp;channel=desktop&amp;div=pngCasinoGame&amp;embedmode=iframe&amp;lobby=https://www.napoleongames.be&amp;origin=https://play-rgs.oryxgaming.com/&amp;isGameBridge=true' and @id = 'gameWindow']</value>
      <webElementGuid>363a98d2-e7b1-4524-92fd-d5f786155beb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
