<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Play with money_iframe</name>
   <tag></tag>
   <elementGuidId>d07f75c6-5323-4c5e-a647-ecc42bdcb628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#app iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>736d7e13-209f-422e-a56d-a5e05fbfb274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4619c93b-b538-4137-8f6f-b3c739f9bc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cfe2d574-4754-46d2-b75c-2e2f193c7822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>81db3179-d693-42e4-87aa-0388935a500a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cb54bd20-d133-4fd5-a38a-e2e84e53b760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kind</name>
      <type>Main</type>
      <value>html</value>
      <webElementGuid>c3dbbaa8-c0cf-4c89-9471-e914cd7d24a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-main&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;maintenance_checker-container&quot;]/div[@class=&quot;game-container casino-game-container&quot;]/div[@class=&quot;game-container-content&quot;]/iframe[@class=&quot;iframe&quot;]</value>
      <webElementGuid>72133ea5-9f40-47b8-bb6f-9cbd2236a278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/iframe</value>
      <webElementGuid>235ec6c1-d67a-439c-8e11-c3c928b7e76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>be37bd1b-12d9-4faf-bb70-4dc9aa619181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
