<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Play with money_fullscreen-in-game-head_1d38de</name>
   <tag></tag>
   <elementGuidId>3908cd5b-b363-4749-8f6e-5c4b60c9a757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.fullscreen-in-game-header__nav-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Play with money'])[1]/preceding::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>cd0ede43-e6b6-4075-96e6-d09626a30d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>3c0cf647-2a97-4773-97ee-dba5128b7444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>635788d1-15a2-4590-86f9-6f331284cc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>f0606bdf-4e65-4ac1-ac68-9c5450644719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fullscreen-in-game-header__nav-icon</value>
      <webElementGuid>5169f981-e77c-412a-9559-c8e322987cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-main&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;maintenance_checker-container&quot;]/div[@class=&quot;game-container casino-game-container&quot;]/header[@class=&quot;fullscreen-in-game-header&quot;]/nav[@class=&quot;fullscreen-in-game-header__nav&quot;]/a[@class=&quot;fullscreen-in-game-header__nav-link&quot;]/svg[@class=&quot;fullscreen-in-game-header__nav-icon&quot;]</value>
      <webElementGuid>0461a807-7d2e-4363-afd9-e6e4cadd5f96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play with money'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>0a518da4-d772-4645-acc5-19a674feb0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Napoleon'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>bb5803a0-2878-4277-8f0d-070f2b2de7e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
