<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Demo</name>
   <tag></tag>
   <elementGuidId>c2b3a171-c978-4e4d-9c37-226673b74434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(4) > div.game > div.game__image-container > div.game__popover > div.animation-wrapper > div.game__popover-content > div.game-details > div.game__popover-buttons > button.btn.btn--transparent.btn--outline-white.btn--md.capitalize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Demo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9fdcdc1-c365-4db0-9085-317672b79cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fe3e5e2c-d90a-4e25-82a6-f53dbfb91752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--transparent btn--outline-white btn--md capitalize</value>
      <webElementGuid>c5b1f76c-f249-4e5f-9821-abf235aba3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Demo </value>
      <webElementGuid>2ff1143b-b395-4556-9b15-17f298da3baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-main has-mobile-subnav&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;maintenance_checker-container&quot;]/div[@class=&quot;casino-base-page&quot;]/div[@class=&quot;vertical-container&quot;]/div[@class=&quot;sections&quot;]/div[@class=&quot;generic-game-section&quot;]/div[@class=&quot;generic-game-section__content&quot;]/div[4]/div[@class=&quot;game&quot;]/div[@class=&quot;game__image-container&quot;]/div[@class=&quot;game__popover&quot;]/div[@class=&quot;animation-wrapper&quot;]/div[@class=&quot;game__popover-content&quot;]/div[@class=&quot;game-details&quot;]/div[@class=&quot;game__popover-buttons&quot;]/button[@class=&quot;btn btn--transparent btn--outline-white btn--md capitalize&quot;]</value>
      <webElementGuid>3b42393c-af2f-4abd-a37e-b1bde2b07f4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[8]</value>
      <webElementGuid>bc669392-c4f8-4db7-9dd0-15a501db0a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[4]/div/div/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>de22f7a4-7f82-4deb-a0a3-c25816e176ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play'])[4]/following::button[1]</value>
      <webElementGuid>ca991b53-1646-43c5-9d38-bf3811b27226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slot, roll, A+'])[2]/following::button[2]</value>
      <webElementGuid>889146d1-01ab-4e55-b117-22ba94a61bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Min. stake: EUR 0.01'])[1]/preceding::button[1]</value>
      <webElementGuid>4380465b-8d4e-4e90-b25e-cc53591ce89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volatility'])[3]/preceding::button[1]</value>
      <webElementGuid>c2b813bb-150a-43c2-92a7-8103d586ec24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>3014ac7e-afbb-425a-bf43-d8cdd7e59291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Demo ' or . = ' Demo ')]</value>
      <webElementGuid>066676da-12cf-46ac-87f8-72952cb06e05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
