<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Abstract Methods</name>
   <tag></tag>
   <elementGuidId>b5cfc952-7ce2-4837-ba18-b5825d5f756e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#method-summary-table-tab3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='method-summary-table-tab3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Abstract Methods&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ea7ecb8-f159-4a76-b1cc-4592a44bf6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>method-summary-table-tab3</value>
      <webElementGuid>8a966d31-5437-48c6-be7f-2645af7c10cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c17cc94c-ed0a-49b1-8a05-347f71c96abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84fe2dfc-b01e-4b6a-95c8-37a108259510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>method-summary-table.tabpanel</value>
      <webElementGuid>069f5254-2562-4b25-ae31-76a637426125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>807a2462-788e-42bc-9eb3-9666a2678511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>switchTab(event)</value>
      <webElementGuid>1e781509-1c4a-44f9-96cc-5d745453b715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show('method-summary-table', 'method-summary-table-tab3', 3)</value>
      <webElementGuid>87901cd3-18e6-446a-8a05-bbc4f496d15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-tab</value>
      <webElementGuid>a0f30a2c-b105-4179-b894-9c977ea7c439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abstract Methods</value>
      <webElementGuid>00fef491-ccbc-4ccf-809c-226c1fdef88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;method-summary-table-tab3&quot;)</value>
      <webElementGuid>79101425-088f-4033-a012-ffac00060b6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='method-summary-table-tab3']</value>
      <webElementGuid>b7eefce0-ea44-4c54-86e7-d25889c1b64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='method-summary-table']/div/button[3]</value>
      <webElementGuid>f16950fa-8d8b-4e9a-a78a-8b1d49dfc482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instance Methods'])[1]/following::button[1]</value>
      <webElementGuid>7f1293ad-99a1-4ed8-8ec9-db2253685ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Methods'])[1]/following::button[2]</value>
      <webElementGuid>9c4443c6-8859-4b70-b1bc-78bc43e34c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modifier and Type'])[1]/preceding::button[1]</value>
      <webElementGuid>113e5801-5125-428b-aa66-f13a81b90138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method'])[3]/preceding::button[1]</value>
      <webElementGuid>d86a4b37-3787-427d-9943-a67e121ce865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Abstract Methods']/parent::*</value>
      <webElementGuid>23a9f034-f52a-4b9c-8cfb-45a53297fc52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>c589275e-1368-488e-bfa6-8b7b4794e318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'method-summary-table-tab3' and (text() = 'Abstract Methods' or . = 'Abstract Methods')]</value>
      <webElementGuid>336ce007-b4ae-4dc6-8dd7-7784b6858e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
